### ISSUE TITLE
Label data format

### ISSUE THREAD

**Issue by pachalamBhasi** [jeasinema/VoxelNet-tensorflow#18]
Hello,
I am quite stuck with the text files containing labels. From KITTI i see that there are tracklets stored as xmls.  Do i need to parse those into some particulat format ?. Any help is appreciated . Thanks in advance

**Comment by turboxin** [comment]
you should probably download "object detection" dataset , which contains training labels of object data set (5 MB) in txt fomat: http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d

**Comment by pachalamBhasi** [comment]
@turboxin. Thanks for the advice.  Let me try that.
