### ISSUE TITLE
ImportError: box_overlaps.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by wangjksjtu** [jeasinema/VoxelNet-tensorflow#23]
I have followed the instructions in README.md, but when I tried to train the module, something went wrong.
```
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from model import RPN3D
  File "/home/xxx/VoxelNet-tensorflow/model/__init__.py", line 12, in <module>                                                                       
    from model.model import *
  File "/home/xxx/VoxelNet-tensorflow/model/model.py", line 17, in <module>                                                                          
    from utils import *
  File "/home/xxx/VoxelNet-tensorflow/utils/__init__.py", line 10, in <module>                                                                       
    from utils.box_overlaps import *
ImportError: /home/xxx/VoxelNet-tensorflow/utils/box_overlaps.so: undefined symbol: _Py_ZeroStruct 
```

I thought it may be due to cython compiling error. But it seems the compilation is successful.
When I ran the setup.py again, I got
```
running build_ext
```
Is there any other way to compile the `box_overlaps.cpp` ?
Can you help me solve this problem? Thanks so much!

**Comment by jeasinema** [comment]
@wangjksjtu Please list the environment informations.

**Comment by wangjksjtu** [comment]
Thanks for your timely reply and I am so sorry to reply so late.
Here are the environment information.

> Ubuntu 16.04
> Python 3.5
> tensorflow-gpu 1.2 (cuda8.0 + cudnn5.1)

I know that the tensorflow version is not compatible, but I wonder is there any solution to run the codes? Thanks.

**Comment by andrewsilva9** [comment]
I had this issue because I forgot to run `python setup.py build_ext --inplace`

Running that resolved the issue for me. I am also on 16.04 with Python 3.5, but I have tensorflow-gpu 1.4 (cuda 8.0 + cudnn5.1).

If you want to install tensorflow-gpu-1.4.0, the link is here: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0rc1-cp35-cp35m-linux_x86_64.whl
From their site: https://www.tensorflow.org/versions/r1.4/install/install_linux#python_35

**Comment by wangjksjtu** [comment]
@andrewsilva9, Thanks so much.
It seems that cudnn 5.1 doesn't support tensorflow-gpu 1.4, which requires cudnn 6.0.
How can I install tf-gpu1.4 without updating cudnn?

**Comment by andrewsilva9** [comment]
I was mistaken about my own setup, I have v6. However, it looks like anything >3 will work, so you should be fine with 5.1. You may need to install from source: https://www.tensorflow.org/versions/r1.4/install/install_sources
