### ISSUE TITLE
ResourceExhaustedError (see above for traceback):

### ISSUE THREAD

**Issue by ashishkumar-rambhatla** [jeasinema/VoxelNet-tensorflow#24]
Hey Jeasinema!

I'm getting the following error when running on a system with 2gb nvidia geforce 940M card with ompute capability  5.0
`ResourceExhaustedError (see above for traceback): OOM when allocating tensor with [shape[1,10,400,352,128]`]
![error](https://user-images.githubusercontent.com/26026036/35991790-4edf944a-0d2e-11e8-87bb-629cee7fe117.png)
can you please tell me if i can run training with my current system configuration. If so, please give me the suitable input arguments with train.py so as to avoid over usage of gpu.

**Comment by jeasinema** [comment]
Hi, 
You need at least one nvidia gpu with more than 6GB memory.
