### ISSUE TITLE
Train with all classes

### ISSUE THREAD

**Issue by LinHungShi** [jeasinema/VoxelNet-tensorflow#25]
Hi thanks for you hard working on this project. Is it possible to train with all the classes at once? If not,  could you give me some hints so that I can figure out my own method?

**Comment by jeasinema** [comment]
Hi,

Have a look at [here](https://github.com/jeasinema/VoxelNet-tensorflow/blob/master/config.py#L32).

**Comment by LinHungShi** [comment]
HI, thank you so much. I have changed DETECT_OBJ to "" to enable all-classes detection. However, it seems I still have to modify the function process_pointcloud since it only addresses car and pedestrian/cyclist, respectively. BTW, it seems the random shuffling of point cloud in preprocess.py does not apply to all cases since it's written in one of if-else conditions. Correct me if I am wrong.

**Comment by jeasinema** [comment]
Hi,

1. Yes, this code can only handle one class at a time. That is because the preprocessing procedures of each class are quite different(refer to 3.1 in the origin paper).

2. Yes, the shuffling operation should not be placed in an if-else statement, fix in f1d0d68.

**Comment by LinHungShi** [comment]
Hi, thanks for the reply. How about shift_coord?

**Comment by ezeddin** [comment]
That's mean I need to have different weights/model for each class? Or just during training I need to change the class?

**Comment by Abhirami20** [comment]
I am also having same problem. Is it possible to make the code train for all three classes; car, pedestrians and cyclists at once?

**Comment by Abhirami20** [comment]
> HI, thank you so much. I have changed DETECT_OBJ to "" to enable all-classes detection. However, it seems I still have to modify the function process_pointcloud since it only addresses car and pedestrian/cyclist, respectively. BTW, it seems the random shuffling of point cloud in preprocess.py does not apply to all cases since it's written in one of if-else conditions. shift_coord also confuses me. From my understanding of the code, point cloud contains (x,y,z,h,w,l,r) coordinates in order, and lidar is the offset of origin along Z,Y,X axes. Therefore, wouldn't shift_coord be written as
> 
> shift_coord = point_cloud[:, 0:3] + lidar[::-1] ?
> 
> Please correct me if I am wrong. Thanks :)

Did you fix it?

**Comment by Abhirami20** [comment]
> HI, thank you so much. I have changed DETECT_OBJ to "" to enable all-classes detection. However, it seems I still have to modify the function process_pointcloud since it only addresses car and pedestrian/cyclist, respectively. BTW, it seems the random shuffling of point cloud in preprocess.py does not apply to all cases since it's written in one of if-else conditions. shift_coord also confuses me. From my understanding of the code, point cloud contains (x,y,z,h,w,l,r) coordinates in order, and lidar is the offset of origin along Z,Y,X axes. Therefore, wouldn't shift_coord be written as
> 
> shift_coord = point_cloud[:, 0:3] + lidar[::-1] ?
> 
> Please correct me if I am wrong. Thanks :)

Is it possible to train all classes or, pedestrian, car and cyclists all at once by editing code?

**Comment by Abhirami20** [comment]
> Hi,
> 
> 1. Yes, this code can only handle one class at a time. That is because the preprocessing procedures of each class are quite different(refer to 3.1 in the origin paper).
> 2. Yes, the shuffling operation should not be placed in an if-else statement, fix in [f1d0d68](https://github.com/jeasinema/VoxelNet-tensorflow/commit/f1d0d6862fbf4a260dfff57c02417a6974cfd728).

By editing code, is it possible to train all classes at once, is, not one at a time but 3( car, pedestrian, and cyclists) at a time?
