### ISSUE TITLE
Applying mask in the VFELayer 

### ISSUE THREAD

**Issue by rmeertens** [jeasinema/VoxelNet-tensorflow#28]
When profiling the runtime I noticed that the tiling of the mask to `mask = tf.tile(mask, [1, 1, 2 * self.units])` takes a long time. I was wondering why this mask is applied, don't empty voxels already get filtered out when selecting the pointcloud? Would love to know if there is any reason behind this code...

**Comment by jeasinema** [comment]
Hi,

This line of code has noting to do with (non-)empty voxels, but redundant points in one voxel. Since some voxels may contain less than `T` points, we just augment them to `T`. After the multiply operation, values coming from such augmented points need to be fixed at zero.
