### ISSUE TITLE
Bug in corner_to_center_box3d function in utils.py

### ISSUE THREAD

**Issue by aseembehl** [jeasinema/VoxelNet-tensorflow#31]
Follwing Line 230 in utils.py

`x, y, z = np.sum(roi, axis=0) / 8
`
should be replaced with the follwoing

```
x = np.sum(roi[:, 0], axis=0)/ 8
y = np.sum(roi[0:4, 1], axis=0)/ 4
z = np.sum(roi[:, 2], axis=0)/ 8
```

This makes sure that the x,y, z is the location of the bottom center of the bounding box.

**Comment by jeasinema** [comment]
Thanks, fix in d24c3ee.

**Comment by LinHungShi** [comment]
Isn't (x,y,z) the center of the bounding box?

**Comment by aseembehl** [comment]
yes (x,y,z) is the bounding box center in the paper. The paper sets the anchor z to -1 m. However, in this implementation the __C.ANCHOR_Z = -1.0 - cfg.ANCHOR_H/2 which means the anchor is at bottom.

Hope that answers your question!

**Comment by LinHungShi** [comment]
Hello, thanks for your answer. But since z is the vertical axis, shouldn't we correct z axis rather than y axis?

**Comment by aseembehl** [comment]
That is because the function `corner_to_center_box3d' operates in the camera coordinate system where the y axis is the up axis.

**Comment by LinHungShi** [comment]
It makes sense. Thanks for your swift reply.
