### ISSUE TITLE
missing activation=False for p_map layer?

### ISSUE THREAD

**Issue by moskewcz** [jeasinema/VoxelNet-tensorflow#33]
i'm having trouble understanding why the p_map layer doesn't have 'activation=False':

https://github.com/jeasinema/VoxelNet-tensorflow/blob/master/model/rpn.py#L98

it's fed into a sigmoid, so if the activations are ReLU'd to be non-negative, it seems the objectness outputs:

https://github.com/jeasinema/VoxelNet-tensorflow/blob/master/model/rpn.py#L104

will be limited to [.5,1]. maybe even if that's a bit wrong-ish, it doesn't much matter somehow?

**Comment by moskewcz** [comment]
see also issue #10 -- i think that issue was meant to apply to both r_map and p_map, but the fix was only applied to r_map. i dunno why the creator of that issue didn't comment further, though, so again maybe i'm just confused.

**Comment by jeasinema** [comment]
Thanks, fix in d24c3ee.
